#include "tray_impl.h"
#include "_cgo_export.h" // Auto-generated by CGO to allow calling Go functions
#import <Cocoa/Cocoa.h>

@interface TrayTarget : NSObject
@end

@implementation TrayTarget
- (void)onShow:(id)sender {
  handleTrayClick(1);
}
- (void)onQuit:(id)sender {
  handleTrayClick(2);
}
- (void)onExport:(id)sender {
  handleTrayClick(3);
}
- (void)onImport:(id)sender {
  handleTrayClick(4);
}
@end

static TrayTarget *target;
static NSStatusItem *statusItem;

void setupTray() {
  dispatch_async(dispatch_get_main_queue(), ^{
    target = [[TrayTarget alloc] init];
    statusItem = [[NSStatusBar systemStatusBar]
        statusItemWithLength:NSVariableStatusItemLength];
    [statusItem retain];

    // Icon
    NSImage *image = [NSImage imageNamed:@"NSApplicationIcon"];
    [image setSize:NSMakeSize(18, 18)]; // Standard tray icon size
    [statusItem.button setImage:image];
    [statusItem.button setTitle:@""];

    NSMenu *menu = [[NSMenu alloc] initWithTitle:@"Thawts"];

    NSMenuItem *showItem = [[NSMenuItem alloc] initWithTitle:@"Show"
                                                      action:@selector(onShow:)
                                               keyEquivalent:@""];
    [showItem setTarget:target];
    [menu addItem:showItem];

    [menu addItem:[NSMenuItem separatorItem]];

    NSMenuItem *exportItem =
        [[NSMenuItem alloc] initWithTitle:@"Export Data..."
                                   action:@selector(onExport:)
                            keyEquivalent:@""];
    [exportItem setTarget:target];
    [menu addItem:exportItem];

    NSMenuItem *importItem =
        [[NSMenuItem alloc] initWithTitle:@"Import Data..."
                                   action:@selector(onImport:)
                            keyEquivalent:@""];
    [importItem setTarget:target];
    [menu addItem:importItem];

    [menu addItem:[NSMenuItem separatorItem]];

    NSMenuItem *quitItem = [[NSMenuItem alloc] initWithTitle:@"Quit"
                                                      action:@selector(onQuit:)
                                               keyEquivalent:@"q"];
    [quitItem setTarget:target];
    [menu addItem:quitItem];

    [statusItem setMenu:menu];
  });
}
