// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {storage} from '../models';

export function Context():Promise<context.Context>;

export function ExportThoughts():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Hide():Promise<void>;

export function ImportThoughts():Promise<void>;

export function Quit():Promise<void>;

export function Save(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<Array<storage.Thought>>;

export function SetTestMode(arg1:boolean):Promise<void>;

export function SetWindowHeight(arg1:number):Promise<void>;

export function Show():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Toggle():Promise<void>;
