// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function ExportThoughts() {
  return window['go']['app']['App']['ExportThoughts']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function Hide() {
  return window['go']['app']['App']['Hide']();
}

export function ImportThoughts() {
  return window['go']['app']['App']['ImportThoughts']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function Save(arg1) {
  return window['go']['app']['App']['Save'](arg1);
}

export function SetTestMode(arg1) {
  return window['go']['app']['App']['SetTestMode'](arg1);
}

export function Show() {
  return window['go']['app']['App']['Show']();
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function Toggle() {
  return window['go']['app']['App']['Toggle']();
}
