// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * CaptureContext holds metadata about the environment when a thought was captured.
 * All fields are populated by the metadata.Provider; defaults to empty strings.
 */
export class CaptureContext {
    /**
     * Creates a new CaptureContext instance.
     * @param {Partial<CaptureContext>} [$$source = {}] - The source object to create the CaptureContext.
     */
    constructor($$source = {}) {
        if (!("window_title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["window_title"] = "";
        }
        if (!("app_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["app_name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureContext instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureContext}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaptureContext(/** @type {Partial<CaptureContext>} */($$parsedSource));
    }
}

/**
 * Intent represents an actionable item extracted from a thought and awaiting
 * user confirmation before being created in a native calendar or reminder app.
 */
export class Intent {
    /**
     * Creates a new Intent instance.
     * @param {Partial<Intent>} [$$source = {}] - The source object to create the Intent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("thought_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["thought_id"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * "calendar" | "task" | "reminder"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["date"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * "pending" | "confirmed" | "dismissed"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Intent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Intent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Intent(/** @type {Partial<Intent>} */($$parsedSource));
    }
}

/**
 * Settings holds user-configurable preferences persisted in the database.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("capture_hotkey" in $$source)) {
            /**
             * CaptureHotkey is the global hotkey for toggling the capture window,
             * encoded as a "+" separated string, e.g. "ctrl+option+space".
             * Supported modifiers: ctrl, alt, option (=alt on macOS), cmd (macOS), shift.
             * Supported keys: space, a-z. Changes take effect immediately.
             * @member
             * @type {string}
             */
            this["capture_hotkey"] = "";
        }
        if (!("review_hotkey" in $$source)) {
            /**
             * ReviewHotkey is the global hotkey for opening review mode (macOS only).
             * Same format as CaptureHotkey. Changes take effect immediately.
             * @member
             * @type {string}
             */
            this["review_hotkey"] = "";
        }
        if (!("launch_at_login" in $$source)) {
            /**
             * LaunchAtLogin controls whether thawts starts automatically on login.
             * Changes take effect immediately.
             * @member
             * @type {boolean}
             */
            this["launch_at_login"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * Tag is a classification label attached to a thought.
 */
export class Tag {
    /**
     * Creates a new Tag instance.
     * @param {Partial<Tag>} [$$source = {}] - The source object to create the Tag.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("thought_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["thought_id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "regex", "ai", "user"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("confidence" in $$source)) {
            /**
             * 0.0–1.0
             * @member
             * @type {number}
             */
            this["confidence"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag(/** @type {Partial<Tag>} */($$parsedSource));
    }
}

/**
 * Thought is the central domain entity.
 * 
 * RawContent is the original text captured from the user — it is immutable (the
 * "shadow record"). Content may be edited later in Review Mode; RawContent never is.
 * Hidden thoughts are filtered from normal views and land in the "Review Needed" bin.
 * Meta holds arbitrary structured metadata (e.g. merged_from for merged thoughts).
 */
export class Thought {
    /**
     * Creates a new Thought instance.
     * @param {Partial<Thought>} [$$source = {}] - The source object to create the Thought.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("raw_content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["raw_content"] = "";
        }
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {CaptureContext}
             */
            this["context"] = (new CaptureContext());
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {Tag[]}
             */
            this["tags"] = [];
        }
        if (!("hidden" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hidden"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["meta"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Thought instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Thought}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField3_0($$parsedSource["context"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField6_0($$parsedSource["meta"]);
        }
        return new Thought(/** @type {Partial<Thought>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = CaptureContext.createFrom;
const $$createType1 = Tag.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
