// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportThoughts() {
  return window['go']['main']['App']['ExportThoughts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function ImportThoughts() {
  return window['go']['main']['App']['ImportThoughts']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}
