// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportThoughts():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Hide():Promise<void>;

export function ImportThoughts():Promise<void>;

export function Quit():Promise<void>;

export function Save(arg1:string):Promise<void>;

export function Show():Promise<void>;

export function Toggle():Promise<void>;
