// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails application adapter. Embed service.Service is promoted so
 * all its exported methods are callable from the frontend via generated JS bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * CleanText returns a typo-corrected version of the thought's content for
 * display purposes only. The original content is never modified.
 * @param {number} id
 * @returns {$CancellablePromise<string>}
 */
export function CleanText(id) {
    return $Call.ByID(2175724842, id);
}

/**
 * ConfirmIntent marks an intent as confirmed and attempts to create a native
 * calendar or reminder entry (macOS only, best-effort).
 * @param {string} intentID
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmIntent(intentID) {
    return $Call.ByID(3499387654, intentID);
}

/**
 * DeleteThought removes a thought permanently.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteThought(id) {
    return $Call.ByID(1850813756, id);
}

/**
 * DismissIntent marks an intent as dismissed.
 * @param {string} intentID
 * @returns {$CancellablePromise<void>}
 */
export function DismissIntent(intentID) {
    return $Call.ByID(4258237266, intentID);
}

/**
 * ExportCSV shows a save-file dialog and exports all thoughts to CSV.
 * @returns {$CancellablePromise<string>}
 */
export function ExportCSV() {
    return $Call.ByID(1228792934);
}

/**
 * ExportJSON shows a save-file dialog and exports all thoughts to JSON.
 * Returns a human-readable summary or an error message.
 * @returns {$CancellablePromise<string>}
 */
export function ExportJSON() {
    return $Call.ByID(2624492816);
}

/**
 * ExportToCSV writes thoughts as CSV to path. Tags are pipe-separated in one column.
 * Returns the number of thoughts exported.
 * @param {string} path
 * @returns {$CancellablePromise<number>}
 */
export function ExportToCSV(path) {
    return $Call.ByID(140316005, path);
}

/**
 * ExportToJSON writes a full JSON snapshot of all thoughts and intents to path.
 * Returns the number of thoughts exported.
 * @param {string} path
 * @returns {$CancellablePromise<number>}
 */
export function ExportToJSON(path) {
    return $Call.ByID(3529090697, path);
}

/**
 * FindRelated returns a thought semantically related to text captured more than
 * 24 hours ago. Returns nil (no error) when nothing qualifies.
 * @param {string} text
 * @returns {$CancellablePromise<domain$0.Thought | null>}
 */
export function FindRelated(text) {
    return $Call.ByID(1606493558, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetHiddenThoughts returns thoughts flagged as mishaps, awaiting user review.
 * @returns {$CancellablePromise<(domain$0.Thought | null)[]>}
 */
export function GetHiddenThoughts() {
    return $Call.ByID(2875679362).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetPendingIntents returns all intents awaiting user confirmation.
 * @returns {$CancellablePromise<domain$0.Intent[]>}
 */
export function GetPendingIntents() {
    return $Call.ByID(1496427802).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetRecentThoughts returns the N most recently saved thoughts.
 * @param {number} limit
 * @returns {$CancellablePromise<(domain$0.Thought | null)[]>}
 */
export function GetRecentThoughts(limit) {
    return $Call.ByID(802394129, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSentimentTrend returns the rolling average sentiment score over the last
 * `days` days. Returns 0 when no signals are recorded.
 * @param {number} days
 * @returns {$CancellablePromise<number>}
 */
export function GetSentimentTrend(days) {
    return $Call.ByID(3107032076, days);
}

/**
 * GetThought returns a single thought by ID.
 * @param {number} id
 * @returns {$CancellablePromise<domain$0.Thought | null>}
 */
export function GetThought(id) {
    return $Call.ByID(2318451921, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * HideWindow hides the application window.
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(872171308);
}

/**
 * ImportCSV shows an open-file dialog and imports thoughts from a CSV file.
 * When restore is true all existing data is deleted before importing.
 * @param {boolean} restore
 * @returns {$CancellablePromise<string>}
 */
export function ImportCSV(restore) {
    return $Call.ByID(508059031, restore);
}

/**
 * ImportFromCSV reads a CSV file from path and imports the thoughts.
 * Expected header columns (case-insensitive): content, raw_content, created_at,
 * updated_at, hidden, tags (pipe-separated), window_title, app_name, url.
 * Only "content" is required. When restore is true existing data is deleted first.
 * Returns the number of thoughts imported.
 * @param {string} path
 * @param {boolean} restore
 * @returns {$CancellablePromise<number>}
 */
export function ImportFromCSV(path, restore) {
    return $Call.ByID(3479343655, path, restore);
}

/**
 * ImportFromJSON reads a JSON snapshot from path and imports it.
 * When restore is true all existing data is deleted first.
 * Returns the number of thoughts imported.
 * @param {string} path
 * @param {boolean} restore
 * @returns {$CancellablePromise<number>}
 */
export function ImportFromJSON(path, restore) {
    return $Call.ByID(2767141515, path, restore);
}

/**
 * ImportJSON shows an open-file dialog and imports thoughts from a JSON file.
 * When restore is true all existing data is deleted before importing.
 * @param {boolean} restore
 * @returns {$CancellablePromise<string>}
 */
export function ImportJSON(restore) {
    return $Call.ByID(2277596667, restore);
}

/**
 * IsCapturing reports whether the window is currently in capture mode.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsCapturing() {
    return $Call.ByID(2535118221);
}

/**
 * IsDialogOpen reports whether a native file dialog is currently open.
 * The focus-loss hide hook must not hide the window while a dialog is open.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDialogOpen() {
    return $Call.ByID(2677586112);
}

/**
 * MergeThoughts combines multiple thoughts into one, soft-deleting the originals.
 * @param {number[]} ids
 * @returns {$CancellablePromise<domain$0.Thought | null>}
 */
export function MergeThoughts(ids) {
    return $Call.ByID(61485542, ids).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PrepareCapture collects active window metadata with a 200ms timeout and
 * stores it for the next SaveThought call. Call this just before showing the
 * capture UI so the context reflects the app that was active before Thawts
 * gained focus.
 * @returns {$CancellablePromise<void>}
 */
export function PrepareCapture() {
    return $Call.ByID(4052146203);
}

/**
 * Quit shuts down the application.
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(149737679);
}

/**
 * RestartApp launches a fresh copy of the binary and quits the current process.
 * @returns {$CancellablePromise<void>}
 */
export function RestartApp() {
    return $Call.ByID(302275134);
}

/**
 * SaveThought persists a thought, then classifies it asynchronously.
 * Returns the saved thought immediately (before classification completes).
 * @param {string} content
 * @returns {$CancellablePromise<domain$0.Thought | null>}
 */
export function SaveThought(content) {
    return $Call.ByID(473542970, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SearchThoughts returns thoughts matching the query string.
 * When query is empty, returns the 20 most recent thoughts.
 * @param {string} query
 * @returns {$CancellablePromise<(domain$0.Thought | null)[]>}
 */
export function SearchThoughts(query) {
    return $Call.ByID(1907645926, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SemanticSearch returns thoughts ranked by semantic similarity to query.
 * Falls back to text search when no embedding model is available.
 * @param {string} query
 * @returns {$CancellablePromise<(domain$0.Thought | null)[]>}
 */
export function SemanticSearch(query) {
    return $Call.ByID(2946308184, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetCaptureHeight resizes the capture window height as the thought list grows.
 * @param {number} h
 * @returns {$CancellablePromise<void>}
 */
export function SetCaptureHeight(h) {
    return $Call.ByID(2362395377, h);
}

/**
 * ShouldHideOnFocusLoss reports whether the focus-loss hook should hide the
 * window. Returns false for a short grace period after the window is shown so
 * that the tray-click or hotkey interaction does not immediately steal focus
 * back before the window has a chance to become active.
 * @returns {$CancellablePromise<boolean>}
 */
export function ShouldHideOnFocusLoss() {
    return $Call.ByID(2112871677);
}

/**
 * ShowCapture switches to capture mode: thin bar, always on top.
 * @returns {$CancellablePromise<void>}
 */
export function ShowCapture() {
    return $Call.ByID(1212881653);
}

/**
 * ShowReview switches to review mode, expanding the window downward.
 * @returns {$CancellablePromise<void>}
 */
export function ShowReview() {
    return $Call.ByID(4046865717);
}

/**
 * ToggleCapture toggles capture mode via the global hotkey.
 * If the window is already visible in capture mode it is hidden; otherwise it
 * is centered on screen and shown. Centers using review dimensions first so
 * that expanding to review later only changes the height.
 * @returns {$CancellablePromise<void>}
 */
export function ToggleCapture() {
    return $Call.ByID(1466966318);
}

/**
 * UnhideThought moves a thought out of the mishap bin.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function UnhideThought(id) {
    return $Call.ByID(4175073444, id);
}

/**
 * UpdateThought edits the visible content of a thought.
 * The original text (shadow record) is preserved.
 * @param {number} id
 * @param {string} content
 * @returns {$CancellablePromise<domain$0.Thought | null>}
 */
export function UpdateThought(id, content) {
    return $Call.ByID(3239951054, id, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = domain$0.Thought.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.Intent.createFrom;
const $$createType4 = $Create.Array($$createType3);
